### ISSUE TITLE
交互要点击两次才能播放音乐

### ISSUE THREAD

**Issue by OriharaIzaya7** [xun19/easy-ring#8]
第一次点击 输出了open the ring和play the ring 但是未有音乐播放，点击第二次又输出了一次play the ring才有音乐播放

**Comment by xun19** [comment]
是Vue组件、React组件，还是方法调用的呢？

**Comment by xun19** [comment]
是Vue组件、React组件，还是方法调用的呢？

**Comment by OriharaIzaya7** [comment]
vue组件

**Comment by xun19** [comment]
是Vue2还是Vue3? 我回头看一下

**Comment by OriharaIzaya7** [comment]
vue3 我在交互的时候同时把open和ring都改为true 但还是没有声音

**Comment by xun19** [comment]
ok，我回去试一下

**Comment by xun19** [comment]
不太建议把open和ring设为true的语句写在同一个交互里。如果一定要这么写，可以这么试试：``

**Comment by xun19** [comment]
我试了一下，确实出现了这个现象，你是不是把open和ring设为true的语句写在同一个交互里了（挨到一块），像这样？

```javascript
open.value = true
ring.value = true
```

这么去设置open和ring不太好，建议把这两个步骤分开到不同的时机（或者说交互）里执行好一些，比如像我demo里写的那样，在询问用户同意的时候设置open，在接收到消息的时候设置ring

但是如果你想要这么用，可以试试这样写：
```javascript
open.value = true
setTimeout(() => ring.value = true)
```
把设置ring的这一步语句弄成异步，应该可以解决

**Comment by OriharaIzaya7** [comment]
是的，按照您的方法成功解决了。感谢您的耐心解答❤
